# =============================================================================
# fritzFlux - Setup & Deployment
# =============================================================================


# --- Local Development Setup ---
command -v python3.13 >/dev/null 2>&1 && PYTHON=python3.13 || PYTHON=python3
$PYTHON -m venv /opt/fritzflux/.venv
source /opt/fritzflux/.venv/bin/activate
pip install --upgrade pip
pip install -r /opt/fritzflux/requirements.txt


# --- BUILD & RUN ---
./opt/fritzflux/docker/build.sh

cd /opt/fritzflux && source .venv/bin/activate && python run.py

# Squash Merge & Tag
Mache ein Squash Merge aller Commits nach main, erstelle einen neuen tag und tagge auf v1.1 und pushe den Tag. Danach löscht du den Feature-Branch lokal und remote.

# Prune
docker system prune -af
docker buildx prune -af
